import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'


export default function Home({data}) {
  return (
  <div className = {styles.container}>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img />
          <a href='/'> Home</a>                
          <a href='/about-us'> About Us</a>
        </nav>
    </header>

    <main className = {styles.main}>
    <a href= "/events/london">
      <img/>
      <h2>Breakfast</h2>
    </a>

  
    <a href= "/events/sanfran">
      <img/>
      <h2>Lunch</h2>
    </a>

    <a href= "/events/barcelona">
      <img/>
      <h2>Drinks</h2>
    </a>
    </main>

<footer className = {styles.footer}></footer>  
</div>  

  );
}

export async function getServerSideProps(){
  const {events_categories}= await import('/data/data.json');
  console.log(events_categories);

  return {
    props:{
      data:events_categories,
    },
  };
}   
